// export const dynamic = 'force-static';
// import products from '../../../../products.json';

import KategorijaProizvoda from '@/components/Pages/KategorijaProizvoda';
import { Product } from '@/@types';
import { Metadata } from 'next';
import { getProducts } from '../../../../sanity/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export async function generateStaticParams() {
  const path = await getProducts({
    query:
      '*[_type == "product" && defined(link[][0]->slug)]{"url": link[][0]->slug}',
  });
  return path;
}
const Kategorija = async ({ params }: { params: { url: string } }) => {
  const products: Product[] = await getProducts({
    query: `*[_type == "product" && link[][0]->slug == "${params.url}"]{
    "id":id.current,
    "tip": tip,
    "name": name,
    "price": cena,
    "detail": details,  
    "image": image.asset->url,
    "novo": novo,
    "akcija": akcija,
    "title": title[][0]->name,
    "link": link[][0]->slug,
    
    }`,
  });
  return <KategorijaProizvoda products={products} />;
};

export default Kategorija;
