// export const dynamic = 'force-static';
export const revalidate = 10;
import KategorijaProizvoda from '@/components/Pages/KategorijaProizvoda';
import { Product } from '@/@types';
import { Metadata } from 'next';
import { getProducts } from '../../../../sanity/utils';
import { url_products_query } from '../../../../sanity/groq-queries';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export async function generateStaticParams() {
  const path = await getProducts({
    query:
      '*[_type == "product" && defined(link[][0]->slug)]{"url": link[][0]->slug}',
  });
  return path;
}
const Kategorija = async ({ params }: { params: { url: string } }) => {
  const products = await getProducts({
    query: url_products_query(params.url),
  });
  return <KategorijaProizvoda products={products} />;
};

export default Kategorija;
