// export const dynamic = 'force-dynamic';
import { H1 } from '@/components/utils';
import { Product } from '@/@types';
import ProductList from '@/components/Pages/ProductList';
import Pagination from '@/components/Pagination';
import { Metadata } from 'next';
export const revalidate = 10;
import { getProducts } from '../../../sanity/utils';
import { ALL_PRODUCTS_QUERY } from '../../../sanity/groq-queries';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const SviProizvodi = async () => {
  const products = await getProducts({
    query: ALL_PRODUCTS_QUERY,
  });

  console.log(products);
  return (
    <>
      <div className={`wrapper w-full  `}>
        <section className="sm:px-5 px-1 ">
          <div className="flex flex-col w-full m-auto  mb-12">
            <H1 className="text-center ">сви производи</H1>
            <ProductList products={products} />
            <Pagination />
          </div>
        </section>
      </div>
    </>
  );
};

export default SviProizvodi;
