// export const dynamic = 'force-dynamic';
import { H1 } from '@/components/utils';
import { Product } from '@/@types';
import ProductList from '@/components/Pages/ProductList';
import Pagination from '@/components/Pagination';
import { Metadata } from 'next';
import { getProducts } from '../../../sanity/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const SviProizvodi = async () => {
  const products: Product[] = await getProducts({
    query: `*[_type == "product"]{
    "id":id.current,
    "tip": tip,
    "name": name, 
    "price": cena,
    "detail": details,
    "image": image.asset->url,
    "novo": novo,
    "akcija": akcija,
    "title": title[][0]->name,
    "link": link[][0]->slug,
  }`,
  });
  return (
    <>
      <div className={`wrapper w-full  `}>
        <section className="sm:px-5 px-1 ">
          <div className="flex flex-col w-full m-auto  mb-12">
            <H1 className="text-center ">сви производи</H1>
            <ProductList products={products} />
            <Pagination />
          </div>
        </section>
      </div>
    </>
  );
};

export default SviProizvodi;
